import { yekan } from "@/utils/fonts";
import "@/tailwind/globals.css";
import PanelAdminLayout from "./components/layout/PanelAdminLayout";
import Providers from "@/redux/Providers";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className} suppressHydrationWarning={true}>
        <Providers>
          <PanelAdminLayout>{children}</PanelAdminLayout>
        </Providers>
        <Toaster
          position="top-center"
          reverseOrder={false}
          gutter={8}
          containerClassName=""
          containerStyle={{
            top:80,
          }}
          toastOptions={{
            // Define default options
            className: "",
            duration: 5000,
            style: {
              background: "#1d3855",
              color: "#fff",
              
            },

            
          }}
        />
      </body>
    </html>
  );
}
