
import { yekan } from "@/utils/fonts";
import  "@/tailwind/globals.css"
import PanelAdminLayout from "./components/layout/PanelAdminLayout";
import Providers from "@/redux/Providers";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
    <body className={yekan.className} suppressHydrationWarning={true}>
    <Providers><PanelAdminLayout>{children}</PanelAdminLayout></Providers>
    </body>
  </html>
  

  )
  
  
}
