import AccountLayout from "@/app/account/components/layout/account-layout/AccountLayout";
import { yekan } from "@/utils/fonts";
import Providers from "@/redux/Providers";

import  "@/tailwind/globals.css"
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
        <body className={yekan.className} suppressHydrationWarning={true}>
        <Providers><AccountLayout>{children}</AccountLayout></Providers>
        </body>
      </html>
    
  ) 
}